[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/basic-crate",
    "crates/extended-crate"
]

[workspace.dependencies]
bootloader_api = "0.11.12" # for bootloader support and its structures