# The following unstable features are common to kernel development.
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# Include the path to the custom target specification file here.
[build]
target = "x86_64-example.json"

[target.'cfg(target_os = "none")']
# The following rust flags are for a higher-half kernel. If you 
# are not building a higher-half kernel, they may not be applicable.
rustflags = [
    "-C", "link-args=--image-base 0xFFFF800000000000",
    "-C", "relocation-model=pic",
    "-C", "code-model=large",
]
# Set the runner as `kboot`
runner = "kboot"
